### ISSUE TITLE
Connect the filter to map

### ISSUE THREAD

**Issue by pengyin-shan** [healthyregions/SDOHPlace#141]

**Comment by mradamcox** [comment]
Providing some more info about this now. We need to be manipulating the map configuration: what layers are visible, what features are highlighted (this is done by updating a layer's style), zoom extent, etc, via the updated search results.

The best case implementation has map object itself is present and methods can be called on it directly when the search results update. Some ways to achieve this would be:

- Figure out a way to pass a new variable through to the map component such that the `mapRef` object within the component performs an action without needing to re-render the whole component.
- Bring the construction of the map to the top-level module, search/index.tsx, and then manipulate it there
- Same as above, but utilize stateless functions in a helper module that take, for example, a layer id and `mapRef` as arguments and then manipulate the map object within that function.

I consider these options, or something along those lines, preferable alternatives to re-rendering the entire map component with a new set of configurations whenever results are updated. This is because I expect that re-rendering would disrupt in-progress panning and zooming, cause unecessary tile loads, and generally have unexpected side-effects. I may be wrong about this, but I think we need to try the other approaches first because they will provide us the greatest flexibility down the road.

**Comment by pengyin-shan** [comment]
Closing this for now and we will discuss more detail after we make directional decisions
