### ISSUE TITLE
Review `handleSearch` to adjust suggestionBuilder once suggestion endpoint is fixed

### ISSUE THREAD

**Issue by pengyin-shan** [healthyregions/SDOHPlace#265]
HandleSearch should be updated to accommodate the new approach, and the suggestionQueryBuilder may need to be removed after HandleSearch is widely adopted for conducting searches exclusively. Review this method after the suggestion endpoint is fixed.

**Comment by pengyin-shan** [comment]
Hi @mradamcox, no rush, but do you have any idea why our suggestion endpoint isn't working? For example, https://solr.sdohplace.org/solr/blacklight-core-dev/suggest?q=education isn’t returning any suggestions. I’m wondering if a re-ingestion might help 🤔

**Comment by mradamcox** [comment]
You are right, it needed to be fully reindexed (all records deleted and then recreated from our JSON metadata records). I assume it stopped working because I had tried some alterations to the schema for the suggestion field, but didn't realized I had to fully reindex to have them be implemented. Thanks for the suggestion!

**Comment by pengyin-shan** [comment]
Great, thank you! Once the `suggest` endpoint is working again, I will refine the updated search methods and fix the autocomplete feature for the search box.

**Comment by mradamcox** [comment]
Ok all set, it is now working on both the Solr cores.

**Comment by pengyin-shan** [comment]
awesome, thanks!
